default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  password: 1234
  username: postgres
  pool: 5

development:
  <<: *default
  database: agenda_api_development

test:
  <<: *default
  database: agenda_api_test
